### ISSUE TITLE
Motor hierarchy needs to be redefined

### ISSUE THREAD

**Issue by mdttrump97** [FTC3486/ftc_app-3486#1]
Currently, the motors are (rather confusingly) separated into lists of leftMotorsWithEncoders, leftMotors (this handles left motors without encoders), rightMotorsWithEncoders, and rightMotors. While it is helpful to divide them by direction, it would be nice if they were all stored in a mater list "motors" which was broken into "leftMotors" and "rightMotors", and then "leftMotors" and "rightMotors" could each be divided into "leftMotorsWithEncoders" and "rightMotorsWithEncoders". 
![motorsissue](https://cloud.githubusercontent.com/assets/11197222/23826355/7e2cc2b6-0660-11e7-8966-bc9af0089c87.png)

**Comment by JacobAMason** [comment]
Would I be helpful to have motorsWithEncoders  and motorsWithoutEncoders?

**Comment by mdttrump97** [comment]
I can't think of a case when we would need to access only the nonencoder motors without also accessing the encoder ones

**Comment by JacobAMason** [comment]
What about allMotorsWithEncoders?

**Comment by JacobAMason** [comment]
Closed by 11be7bd6af51a35fd298b1e9403b3e57ac7f74c6
